

GET http://localhost:9002

Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTYyNDgzNzcsImV4cCI6MTY5NjI0ODQzNywiYXVkIjoiNjUxODE2ZjliZmEwNTY0MjM5NWU5ZjhkIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.T5unus5gFuxRUMThR5Jf394EVydYHl7yt2XKgGSwN_E

POST  http://localhost:9002/auth/login
Content-Type: application/json

{
     "email":"qazikhan@gmail.com",
     "password":"1212"
}
###

POST  http://localhost:9002/auth/refreshtoken

Content-Type: application/json

{
     "refrehtoken":
}
